# Generated by Django 5.2.3 on 2025-07-10 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authontication', '0002_user_district_user_mobile_user_name_user_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
