# Generated by Django 5.2.3 on 2025-07-02 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.category'),
        ),
        migrations.AddField(
            model_name='crop',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
